<?php
//Viết 1 lớp manager kế thừa lớp Employee. Thêm cho nó thuộc tính department_code và hàm set get tương ứng.
//Sử dụng: Tạo mới lớp Manage , setName và dùng toString để hiển thị nhân viên.
//với lớp Manage thì phải overwrite lại hàm toString để hiển thị thêm Mã phòng ban

class Employee
{
    private $name, $age, $phone;

    public function setName(string $name)
    {
        $this->name = $name;
    }

    public function setAge($age)
    {
        $this->age = $age;
    }

    public function setPhone($phone)
    {
        $this->phone = $phone;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getAge()
    {
        return $this->age;
    }

    public function getPhone()
    {
        return $this->phone;
    }


    public function toString()
    {
        echo "Name: " . $this->name . "<br>";
        echo "Age: " . $this->age . "<br>";
        echo "Phone: " . $this->phone . "<br>";
    }
}

class Manage extends Employee
{
    private $department_code;

    public function setdepartment_code($department_code)
    {
        $this->department_code = $department_code;
    }

    public function getdepartment_code()
    {
        return $this->department_code;
    }

    public function toString()
    {
        parent::toString(); // TODO: Change the autogenerated stub
        echo "Department_code: " . $this->department_code;
    }

}

$employee1 = new Manage();
$employee1->setName('Phạm Thị Mai');
$employee1->setAge(23);
$employee1->setPhone(123456789);
$employee1->setdepartment_code(123);

$employee1->toString();